# Generated by Django 4.0.2 on 2022-03-06 18:19

import apps.warehouse.models
import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_delete_machine_delete_mold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0002_materialwarehouse_warehouse_delete_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialwarehouse',
            options={'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 6, 18, 19, 31, 22079, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ColorWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=apps.warehouse.models.set_null, to='data.color', verbose_name='Color')),
                ('supplier', models.ForeignKey(on_delete=apps.warehouse.models.set_null, to='data.supplier', verbose_name='Supplier')),
                ('user', models.ForeignKey(on_delete=apps.warehouse.models.set_null, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('warehouse', models.ForeignKey(on_delete=apps.warehouse.models.set_null, to='warehouse.warehouse', verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
            },
        ),
    ]
