# Generated by Django 4.0.2 on 2022-03-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_materialwarehouse_options_warehouse_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorwarehouse',
            options={'verbose_name': 'Color Warehouse', 'verbose_name_plural': 'Color Warehouses'},
        ),
        migrations.AlterModelOptions(
            name='materialwarehouse',
            options={'verbose_name': 'Material Warehouse', 'verbose_name_plural': 'Material Warehouses'},
        ),
    ]
