# Generated by Django 4.0.3 on 2022-04-05 09:10

import apps.warehouse.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0016_alter_commaterial_options'),
        ('warehouse', '0005_alter_colorwarehouse_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComMaterialWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('com_material', models.ForeignKey(on_delete=apps.warehouse.models.set_null, to='data.commaterial', verbose_name='ComMaterial')),
                ('supplier', models.ForeignKey(on_delete=apps.warehouse.models.set_null, to='data.supplier', verbose_name='Supplier')),
                ('user', models.ForeignKey(on_delete=apps.warehouse.models.set_null, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('warehouse', models.ForeignKey(on_delete=apps.warehouse.models.set_null, to='warehouse.warehouse', verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'ComMaterial Warehouse',
                'verbose_name_plural': 'ComMaterial Warehouses',
            },
        ),
    ]
