# Generated by Django 4.0.3 on 2022-04-05 09:54

import apps.warehouse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_commaterial_options'),
        ('warehouse', '0006_commaterialwarehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorwarehouse',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=apps.warehouse.models.set_null, to='data.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='commaterialwarehouse',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=apps.warehouse.models.set_null, to='data.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='materialwarehouse',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=apps.warehouse.models.set_null, to='data.supplier', verbose_name='Supplier'),
        ),
    ]
