# Generated by Django 4.0.3 on 2022-04-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_alter_colorwarehouse_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorwarehouse',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='commaterialwarehouse',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='materialwarehouse',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount'),
        ),
    ]
