# Generated by Django 4.0.2 on 2022-03-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mold', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mold1',
            new_name='Mold',
        ),
    ]
