# Generated by Django 4.0.2 on 2022-03-08 13:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mold', '0003_mold_created_at_mold_created_by_mold_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mold',
            name='security_detail',
        ),
        migrations.RemoveField(
            model_name='mold',
            name='technical_detail',
        ),
        migrations.AddField(
            model_name='mold',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Detail'),
        ),
    ]
