# Generated by Django 4.0.2 on 2022-03-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mold', '0004_remove_mold_security_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mold',
            name='eye_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
