"""
Django settings for source project.

Generated by 'django-admin startproject' using Django 3.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _
from neomodel import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ajjp9pcyn+$6g#2d86pp2@wrz+o&+n8k@m-xhu#m3l8qj#xc+^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # "bootstrap5",
    # "admin_interface",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'graphene_django',
    'django_neomodel',
    'django.contrib.humanize',
    'colorfield',
    # 'django.contrib.sites',
    # 'rest_framework',
    "corsheaders",
    'ckeditor',
    'default',
    # 'apps.user',
    'apps.data',
    'apps.employee',
    'apps.product',
    'apps.warehouse',
    'apps.company',
    'apps.location',
    'apps.mold',
    'apps.machine',
    'apps.order',
    'apps.workflow',
    'admin_reorder',
    'apps.home'
    
    
]

LOGIN_REDIRECT_URL = "home"  # Route defined in home/urls.py
LOGOUT_REDIRECT_URL = "home"  # Route defined in home/urls.py


ADMIN_REORDER = (

    {'app': 'data', 'models': (
        'data.Supplier',
        'data.Unit',
        'data.Material',
        'data.Color',
        'data.ComMaterial',
        'data.ComMaterialType',
    )},

    'product',
    'employee',
    'location',
    'machine',
    'warehouse',
    'company',
    'mold',
    'order',
    'workflow',
    'auth',
    'default'
)



SITE_ID=1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',
]

ROOT_URLCONF = 'source.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'source.wsgi.application'
# AUTH_USER_MODEL='apps.user.User'
CORS_ALLOW_CREDENTIALS= True


X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

NEOMODEL_NEO4J_BOLT_URL = os.environ.get('NEO4J_BOLT_URL','bolt://neo4j:neo4jpass@localhost:7687')
# you are free to add this configurations
NEOMODEL_SIGNALS = True
NEOMODEL_FORCE_TIMEZONE = False
NEOMODEL_ENCRYPTED_CONNECTION = True
NEOMODEL_MAX_POOL_SIZE = 50

NEOADMIN_HOME = '/neoadmin/'

LOCALE_PATHS = [
    # os.path.join(BASE_DIR, "locale"),
    os.path.join(BASE_DIR, "apps/data/locale"),
    os.path.join(BASE_DIR, "apps/employee/locale"),
    os.path.join(BASE_DIR, "apps/product/locale"),
    os.path.join(BASE_DIR, "apps/warehouse/locale"),
    os.path.join(BASE_DIR, "apps/company/locale"),
    os.path.join(BASE_DIR, "apps/location/locale"),
    os.path.join(BASE_DIR, "apps/mold/locale"),
    os.path.join(BASE_DIR, "apps/machine/locale"),
    os.path.join(BASE_DIR, "apps/order/locale"),
    os.path.join(BASE_DIR, "apps/workflow/locale"),
]

GRAPHENE = {
    'SCHEMA': 'source.schema.schema',
    'MIDDLEWARE': [
        'graphql_jwt.middleware.JSONWebTokenMiddleware',
    ],
}

GRAPHENE_DJANGO_EXTRAS = {
    'DEFAULT_PAGINATION_CLASS': 'graphene_django_extras.paginations.LimitOffsetGraphqlPagination',
    'DEFAULT_PAGE_SIZE': 20,
    'MAX_PAGE_SIZE': 50,
    'CACHE_ACTIVE': True,
    'CACHE_TIMEOUT': 300    # seconds
}

config.DATABASE_URL = 'bolt://neo4j:neo4jpass@localhost:7687'


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False
TIME_ZONE = 'Asia/Tehran'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'login'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static")
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)


# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media').replace('\\', '/')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CKEDITOR_UPLOAD_PATH = 'content/ckeditor/'


CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:3000",
]
CORS_ALLOW_ALL_ORIGINS = True
