# Generated by Django 4.0.2 on 2022-03-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='parent',
        ),
    ]
