# Generated by Django 4.0.2 on 2022-03-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_status_delete_orderstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedOrdres',
            fields=[
            ],
            options={
                'verbose_name': 'Closed order',
                'verbose_name_plural': 'Closed orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
        migrations.CreateModel(
            name='NewOrdres',
            fields=[
            ],
            options={
                'verbose_name': 'New order',
                'verbose_name_plural': 'New orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
        migrations.CreateModel(
            name='OpenOrdres',
            fields=[
            ],
            options={
                'verbose_name': 'Open order',
                'verbose_name_plural': 'Open orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
        migrations.CreateModel(
            name='ReturnedOrdres',
            fields=[
            ],
            options={
                'verbose_name': 'Returned order',
                'verbose_name_plural': 'Returned orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'New orders'), (2, 'Open orders'), (3, 'Closed orders'), (4, 'Returned orders')], default=1, verbose_name='Status'),
        ),
    ]
