# Generated by Django 4.0.3 on 2022-05-11 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_colorwarehouse_amount_and_more'),
        ('data', '0018_imagetype_image_order_id_image_image_type'),
        ('order', '0007_closedordres_newordres_openordres_returnedordres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.commaterial', verbose_name='Bag'),
        ),
        migrations.AddField(
            model_name='order',
            name='barkod',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Barkod'),
        ),
        migrations.AddField(
            model_name='order',
            name='box_pieces',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pieces in box'),
        ),
        migrations.AddField(
            model_name='order',
            name='box_size',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Box size'),
        ),
        migrations.AddField(
            model_name='order',
            name='conditions',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Colditions'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Delivery address'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_mode',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Delivery mode'),
        ),
        migrations.AddField(
            model_name='order',
            name='eticket',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Eticket'),
        ),
        migrations.AddField(
            model_name='order',
            name='has_bag',
            field=models.BooleanField(default=False, verbose_name='Has bag'),
        ),
        migrations.AddField(
            model_name='order',
            name='inner_box_size',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Inner box size'),
        ),
        migrations.AddField(
            model_name='order',
            name='seperator',
            field=models.BooleanField(default=False, verbose_name='Seperator'),
        ),
        migrations.AddField(
            model_name='order',
            name='special_box',
            field=models.BooleanField(default=False, verbose_name='Special box'),
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_percent', models.CharField(default=0, max_length=10, verbose_name='Color percent')),
                ('has_silk', models.BooleanField(default=False, verbose_name='Has silk')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.colorwarehouse', verbose_name='Color')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order product',
                'verbose_name_plural': 'Order products',
            },
        ),
        migrations.CreateModel(
            name='OrderComMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.commaterialwarehouse', verbose_name='Commercial material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order commercial material',
                'verbose_name_plural': 'Order commercial materials',
            },
        ),
    ]
