# Generated by Django 4.0.3 on 2022-05-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_bag_order_barkod_order_box_pieces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Order at'),
        ),
    ]
