# Generated by Django 4.0.3 on 2022-05-18 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_delete_imagetype'),
        ('order', '0009_order_order_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product'),
            preserve_default=False,
        ),
    ]
