# Generated by Django 4.0.3 on 2022-06-26 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_imagetype_image_order_id_image_image_type'),
        ('order', '0011_alter_orderproducts_color_alter_orderproducts_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercommaterial',
            name='material',
        ),
        migrations.AddField(
            model_name='ordercommaterial',
            name='com_material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.commaterial', verbose_name='Commercial material'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.color', verbose_name='Color'),
        ),
    ]
