# Generated by Django 4.0.3 on 2022-08-10 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_orderproducts_color_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Open'), (3, 'Closed'), (4, 'Returned')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderProducts', to='order.order', verbose_name='Order'),
        ),
    ]
