# Generated by Django 4.0.2 on 2022-02-09 11:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Mission title')),
                ('detail', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Detail')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20, verbose_name='Employee code')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Employee full name')),
                ('detail', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Detail')),
                ('mission', models.ManyToManyField(blank=True, null=True, to='employee.Mission', verbose_name='Mission')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
