# Generated by Django 4.0.2 on 2022-02-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Full name'),
        ),
    ]
