# Generated by Django 4.0.2 on 2022-02-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mission',
            field=models.ManyToManyField(to='employee.Mission', verbose_name='Mission'),
        ),
    ]
