# Generated by Django 4.0.2 on 2022-02-09 16:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SemiProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20, verbose_name='Semi product code')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Semi product name')),
                ('detail', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Detail')),
            ],
            options={
                'verbose_name': 'Semi product',
                'verbose_name_plural': 'Semi products',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20, verbose_name='Product code')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Product name')),
                ('detail', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Detail')),
                ('semi_products', models.ManyToManyField(to='product.SemiProduct', verbose_name='Semi products')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
