# Generated by Django 4.0.2 on 2022-02-13 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_semi_products_product_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_last_product',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is last product?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Parent product'),
        ),
    ]
