# Generated by Django 4.0.2 on 2022-02-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_is_last_product_alter_product_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_last_product',
            field=models.BooleanField(default=0, verbose_name='Is last product?'),
            preserve_default=False,
        ),
    ]
