# Generated by Django 4.0.2 on 2022-03-02 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_is_last_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SemiProduct',
        ),
    ]
