# Generated by Django 4.0.2 on 2022-03-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_delete_semiproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_last_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parent',
        ),
    ]
