# Generated by Django 4.0.2 on 2022-03-06 18:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_is_last_product_remove_product_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20, verbose_name='Middle product code')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Middle product name')),
                ('detail', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Detail')),
            ],
            options={
                'verbose_name': 'Middle product',
                'verbose_name_plural': 'Middle products',
            },
        ),
    ]
