# Generated by Django 4.0.2 on 2022-03-06 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_delete_machine_delete_mold'),
        ('product', '0008_delete_middleproduct_product_is_last_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='com_material',
            field=models.ManyToManyField(to='data.ComMaterial'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.material', verbose_name='Material'),
        ),
    ]
