# Generated by Django 4.0.2 on 2022-03-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_com_material_product_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='detail',
        ),
    ]
