# Generated by Django 4.0.2 on 2022-03-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_last_product',
        ),
    ]
