# Generated by Django 4.0.2 on 2022-03-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_producttype_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
