# Generated by Django 4.0.2 on 2022-03-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_commaterial_options'),
        ('product', '0014_alter_producttype_options_product_material_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='com_material',
            field=models.ManyToManyField(to='data.ComMaterial', verbose_name='Commercial material'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount'),
        ),
    ]
