# Generated by Django 4.0.2 on 2022-03-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_commaterial_options'),
        ('product', '0015_alter_product_com_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='com_material',
            field=models.ManyToManyField(blank=True, null=True, to='data.ComMaterial', verbose_name='Commercial material'),
        ),
    ]
