# Generated by Django 4.0.2 on 2022-03-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_commaterial_options'),
        ('product', '0016_alter_product_com_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemiProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Semi product',
                'verbose_name_plural': 'Semi products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='com_material',
            field=models.ManyToManyField(blank=True, to='data.ComMaterial', verbose_name='Commercial material'),
        ),
    ]
