# Generated by Django 4.0.2 on 2022-03-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_semiproduct_product_image_alter_product_com_material'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductType',
            new_name='Department',
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='department',
        ),
    ]
