# Generated by Django 4.0.3 on 2022-04-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_commaterial_options'),
        ('product', '0019_alter_product_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_material_amount', models.IntegerField(blank=True, null=True, verbose_name='Amount')),
                ('com_material', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='data.commaterial', verbose_name='Commercial material')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Commercial material')),
            ],
            options={
                'verbose_name': 'Product com material',
                'verbose_name_plural': 'Product com materials',
            },
        ),
    ]
