# Generated by Django 4.0.3 on 2022-04-05 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_productcommaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='com_material',
        ),
        migrations.AddField(
            model_name='product',
            name='com_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_com_material', to='product.productcommaterial', verbose_name='Commercial material'),
        ),
    ]
