# Generated by Django 4.0.3 on 2022-04-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_delete_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageType',
        ),
    ]
