# Generated by Django 4.0.2 on 2022-03-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigation',
            options={'verbose_name': 'Navigation', 'verbose_name_plural': 'Navigations'},
        ),
    ]
