# Generated by Django 4.0.2 on 2022-03-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_company_region'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
