# Generated by Django 4.0.2 on 2022-03-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_remove_region_city_delete_city_delete_region'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City_1',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='Region_1',
            new_name='Region',
        ),
    ]
