# Generated by Django 4.0.2 on 2022-03-07 15:16

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0013_delete_machine_delete_mold'),
        ('mold', '0003_mold_created_at_mold_created_by_mold_updated_at'),
        ('employee', '0003_alter_employee_mission'),
        ('order', '0004_alter_order_options_alter_order_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machine', '0002_rename_machine1_machine'),
        ('product', '0013_alter_producttype_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_time', models.IntegerField(blank=True, null=True, verbose_name='Cycle time')),
                ('color_rate', models.IntegerField(blank=True, null=True, verbose_name='Color rate')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started at')),
                ('wsp', models.BooleanField(verbose_name='Witness Sample Placed')),
                ('qcfp', models.BooleanField(verbose_name='Quality Control Form Posted')),
                ('wop', models.BooleanField(verbose_name='Work Order Posted')),
                ('rkeg', models.BooleanField(verbose_name='Required Knowledge/Education. given')),
                ('detail', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Detail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.color', verbose_name='Color')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine', verbose_name='Machine')),
                ('machine_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_operator', to='employee.employee', verbose_name='Machine operator')),
                ('mold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mold.mold', verbose_name='Mold')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
                ('quality_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_control', to='employee.employee', verbose_name='Quality control')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
            },
        ),
    ]
