# Generated by Django 4.0.2 on 2022-03-08 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_mission'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='started_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='started_by', to='employee.employee', verbose_name='Started by'),
            preserve_default=False,
        ),
    ]
