# Generated by Django 4.0.2 on 2022-02-08 19:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mold code')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mold name')),
                ('technical_detail', ckeditor.fields.RichTextField(verbose_name='Technical detail')),
                ('security_detail', ckeditor.fields.RichTextField(verbose_name='Security detail')),
            ],
            options={
                'verbose_name': 'Mold',
                'verbose_name_plural': 'Molds',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Supplier name')),
                ('addres', models.CharField(blank=True, max_length=200, null=True, verbose_name='address')),
                ('telephone', models.CharField(blank=True, max_length=200, null=True, verbose_name='telephone')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Material code')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Material name')),
                ('technical_detail', ckeditor.fields.RichTextField(verbose_name='Technical detail')),
                ('security_detail', ckeditor.fields.RichTextField(verbose_name='Security detail')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Raw material',
                'verbose_name_plural': 'Raw materials',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Color code')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Color name')),
                ('technical_detail', ckeditor.fields.RichTextField(verbose_name='Technical detail')),
                ('security_detail', ckeditor.fields.RichTextField(verbose_name='Security detail')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
    ]
