# Generated by Django 4.0.2 on 2022-02-09 10:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Machine code')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Machine name')),
                ('technical_detail', ckeditor.fields.RichTextField(verbose_name='Technical detail')),
                ('security_detail', ckeditor.fields.RichTextField(verbose_name='Security detail')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
            },
        ),
    ]
