# Generated by Django 4.0.2 on 2022-02-09 10:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(default=0, max_length=20, verbose_name='Color code'),
        ),
        migrations.AlterField(
            model_name='color',
            name='security_detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Security detail'),
        ),
        migrations.AlterField(
            model_name='color',
            name='technical_detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Technical detail'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(default=0, max_length=20, verbose_name='Machine code'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='security_detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Security detail'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='technical_detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Technical detail'),
        ),
        migrations.AlterField(
            model_name='material',
            name='code',
            field=models.CharField(default=0, max_length=20, verbose_name='Material code'),
        ),
        migrations.AlterField(
            model_name='material',
            name='security_detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Security detail'),
        ),
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='material',
            name='technical_detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Technical detail'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='code',
            field=models.CharField(default=0, max_length=20, verbose_name='Mold code'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='security_detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Security detail'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='technical_detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Technical detail'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Supplier name'),
            preserve_default=False,
        ),
    ]
