# Generated by Django 4.0.2 on 2022-02-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_color_code_alter_color_security_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(default='', max_length=20, verbose_name='Color code'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(default='', max_length=20, verbose_name='Machine code'),
        ),
        migrations.AlterField(
            model_name='material',
            name='code',
            field=models.CharField(default='', max_length=20, verbose_name='Material code'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='code',
            field=models.CharField(default='', max_length=20, verbose_name='Mold code'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Supplier name'),
        ),
    ]
