# Generated by Django 4.0.2 on 2022-02-23 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.unit', verbose_name='Unit'),
        ),
    ]
