# Generated by Django 4.0.2 on 2022-02-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_material_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='alarm_inventory',
            field=models.IntegerField(blank=True, null=True, verbose_name='Alarm inventory'),
        ),
    ]
