# Generated by Django 4.0.2 on 2022-02-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_material_alarm_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='supplier',
        ),
    ]
