# Generated by Django 4.0.2 on 2022-03-02 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_remove_material_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='supplier',
        ),
    ]
