# Generated by Django 4.0.2 on 2022-03-03 12:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_city_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComMaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Commercial material type',
                'verbose_name_plural': 'Commercial material types',
            },
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='ComMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20, verbose_name='Commercial material code')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Commercial material name')),
                ('alarm_inventory', models.IntegerField(blank=True, null=True, verbose_name='Alarm inventory')),
                ('technical_detail', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Technical detail')),
                ('security_detail', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Security detail')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.commaterialtype', verbose_name='Commercial material type')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Raw material',
                'verbose_name_plural': 'Raw materials',
            },
        ),
    ]
