# Generated by Django 4.0.2 on 2022-03-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_region'),
        ('data', '0011_commaterialtype_alter_unit_name_commaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
