# Generated by Django 4.0.2 on 2022-03-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_remove_region_city_delete_city_delete_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Mold',
        ),
    ]
