# Generated by Django 4.0.2 on 2022-03-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_alter_color_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commaterial',
            options={'verbose_name': 'Commercial material', 'verbose_name_plural': 'Commercial materials'},
        ),
    ]
