# Generated by Django 4.0.2 on 2022-03-02 21:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='Company name')),
                ('tax_admin', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tax administration')),
                ('tax_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tax number')),
                ('billing_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Billing address')),
                ('shipping_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Shipping address')),
                ('province', models.CharField(blank=True, max_length=200, null=True, verbose_name='Province')),
                ('region', models.CharField(blank=True, max_length=200, null=True, verbose_name='Region')),
                ('telephone1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telephone 1')),
                ('telephone2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telephone 2')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
