# Generated by Django 4.0.2 on 2022-03-03 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('company', '0002_remove_company_province_alter_company_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.region', verbose_name='Region'),
        ),
    ]
