# Generated by Django 4.0.2 on 2022-03-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='region',
        ),
    ]
