# Generated by Django 4.0.2 on 2022-03-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Company name'),
        ),
    ]
