# Generated by Django 4.0.2 on 2022-03-08 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_rename_city_1_city_rename_region_1_region'),
        ('company', '0006_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.city', verbose_name='City'),
        ),
    ]
