# Generated by Django 4.0.2 on 2022-03-03 15:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20, verbose_name='Machine code')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Machine name')),
                ('technical_detail', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Technical detail')),
                ('security_detail', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Security detail')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
            },
        ),
    ]
