# Generated by Django 4.0.2 on 2022-03-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_rename_machine1_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='security_detail',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='technical_detail',
        ),
    ]
