# Generated by Django 4.0.3 on 2022-08-10 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0003_remove_machine_security_detail_and_more'),
        ('mold', '0006_alter_mold_eye_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Maintenance')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.machine', verbose_name='Machine')),
                ('mold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mold.mold', verbose_name='Mold')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenance',
            },
        ),
    ]
